### ISSUE TITLE
Will this ever exist?

### ISSUE THREAD

**Issue by nativeit** [etesync/EteSync-4-TbSync#1]
Just curious. Thanks!

**Comment by jobisoft** [comment]
Yes. But this year has been a mess so far and since a few weeks I started a new job (Thunderbird add-on support engineer) and I need to get a few things started. I am devoted to this.

**Comment by tasn** [comment]
I'm closing this ticket as the question has been answered. I also can't wait for the Thunderbird module! :tada:
