### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by VictorVow** [etesync/EteSync-4-TbSync#2]
I was really anticipating this module at the end of last year but it seems 7 months have gone by without any activity.

**Comment by jobisoft** [comment]
Dayjob + Family + Pandemic pretty much used up my time.

**Comment by VictorVow** [comment]
I mean to ask if there's a point soon at which you'll be free to work on this or does it need to be passed on to a new maintainer?

**Comment by jobisoft** [comment]
Before this can get any further, TbSync itself has to survive the transition to TB91.
https://github.com/jobisoft/TbSync/commits/PortBased
